Seção "O que é o GRACE"
petsi-each/Grace-Website pull request #17
Opened 2024-05-22 14:20 UTC by segalv

# ✨ Pull Request 💻

## :dart: Detalhes do Pull Request:

Pendências: Adicionar os elementos representantes das atividades (imagens) e corrigir a altura do svg de background da section.

Fixes #4

## :bomb: Alterações e breaking changes:

- Adição do vetor de background da seção;
- Adição dos elementos textuais independentes da seção;
- Transferência do padding horizontal (px-8) de /src/app/layout.tsx (linha 20) para /src/components/Header.tsx (linha 43);
- **Breaking changes**: Reorganização/criação de diretorios para melhor organização do código: ' /public/home '  e  ' /src/components/home '. Atenção ao importar componentes;

##  :camera_flash: Screenshots:

![image](https://github.com/petsi-each/Grace-Website/assets/148593673/54aefbcf-d2ab-4c96-8392-156a3c35f929)

![image](https://github.com/petsi-each/Grace-Website/assets/148593673/f22e2ec6-f735-4195-9b68-816ed6bd4c16)

![image](https://github.com/petsi-each/Grace-Website/assets/148593673/6aa76a91-f50c-4087-a534-8893d1f8b82c)

2024-05-27 02:07 UTC, Anemaygi commented
![image](https://github.com/petsi-each/Grace-Website/assets/62656745/0943bc61-2715-443e-b825-2a9dba8cf735)

Temos que ver como deixar a imagem adaptável com o conteúdo


Gostei bastante de como implementou o Balao como um componente separado!! Achei que isso deixou o código bem mais fácil de entender!! E tá muito bonitinho tbbbbb

2024-05-28 09:32 UTC, Anemaygi requested changes
:hugs: **Feedback:**

No geral, gostei bastante de como implementou o Balao como um componente separado e seu código tá bem feito! Achei que isso deixou o código bem mais fácil de entender tb :) Tá bem legall, parabénssss :D 

Os ajustes são pequenas coisinhas para facilitar o entendimento do código. Qualquer dúvida, fica à vontade p/ avisar!
Fique à vontade para ver quais ajustem vc quer seguir ou não nesse caso

2024-05-28 09:32 UTC, Anemaygi commented on src/components/home/Oqueeograce.tsx
> +import Balao from "./componentesAuxiliares/Balao";
**🔨 Ajuste:**

poderia colocar o nome da pasta de ./components? p gnt deixar padronizado em todas as páginas :)

2024-05-28 09:32 UTC, Anemaygi commented on src/components/home/componentesAuxiliares/Balao.tsx
> +'use cliente'
**🔨 Ajuste:**

Não precisa do 'use client' aqui!

O use client é utilizado quando a gente precisa de interatividade do lado do cliente (por exemplo, quando a gente usa useState, igua, no menu)

No caso desse componente, como não temos essa interatividade, não precisa do use client (ele vai ser indiferente!!)

https://nextjs.org/docs/app/building-your-application/rendering/client-components

2024-05-28 09:32 UTC, Anemaygi commented on src/components/home/Oqueeograce.tsx
> +'use client'
**🔨 Ajuste:**

Não precisa do use client aqui tb!

2024-05-28 09:32 UTC, Anemaygi commented on src/components/home/Oqueeograce.tsx
> +                        <Balao imagem="/home/oficinasTecnicas.svg" alternativo="Estudantes em computadores" titulo="Oficinas Técnicas" descricao="Para ensino fundamental, médio e graduação" />
**:cloud: Sugestão | :hammer: Ajuste**

Para não precisar repetir o código do Balao 6 vezes, você pode criar uma lista com os valores que precisa e fazer um map (tipo um for each) nessa lista

Ex:

https://github.com/petsi-each/Grace-Website/blob/4d78eed70e4f1fc55c04386322aaa574460bd168/src/components/Header.tsx

2024-05-28 09:32 UTC, Anemaygi commented on public/home/escapeRoom.svg
**:cloud: Sugestão:**

Se derr, seria bom mudar essas imagens que são fotos para JPG/PNGs 

A gnt geralmente usa os SVGs p ícones e p elementos q a gnt quer estilizar no código (tipo o background), mas p fotos no geral (q tem bastante informação), é melhor usar jpg!

2024-05-28 09:32 UTC, Anemaygi commented on src/components/home/componentesAuxiliares/Balao.tsx
> +export default function Balao({ imagem, alternativo, titulo, descricao }:Balaopropos) {
**:hammer: Ajuste:**

Em vez de receber várias props separadamente (imagem, alternativo, titulo, descricao....), você pode receber um objeto contendo tudo isso!

ex:

`export default function Balao(item:Balaopropos)`
 
Aí, quando for importar, vc faz:

<Balao item={item}> 

item seria um objeto contendo imagem, alternativo, título, etc...
Aí, dentro do componente, você pode usar item.imagem, item.alternativo.... etccc

Exemplo do jun: https://github.com/petsi-each/Grace-Website/pull/18/files#diff-7ab3b6f9980b8e9f8d053334e7bacc814dc9b4a111636295ccc86f5bdb1e3bfa

No componente MediaCard, ele recebe objetos com src, alt, title, etc....

2024-05-28 09:32 UTC, Anemaygi commented on src/components/home/componentesAuxiliares/Balao.tsx
> +        <div className="flex flex-col p-6 w-72 h-72 bg-brancoGrace rounded-3xl shadow-md"> {/*queria ter usado o justify center aqui mas nao deu certo com a imagem! */}
**🔨 Ajuste:**

Lembrando de usar HTML semântico!

Ao invés de usar `<div>` (não semântico), usar outras tags (como `<section>`, `<article>`, etc)

https://www.w3schools.com/html/html5_semantic_elements.asp

2024-05-29 03:42 UTC, segalv commented on src/components/home/componentesAuxiliares/Balao.tsx
> +export default function Balao({ imagem, alternativo, titulo, descricao }:Balaopropos) {
A vantagem desse tipo de implementação seria a melhora na legibilidade?

2024-05-30 00:10 UTC, Anemaygi commented on src/components/home/componentesAuxiliares/Balao.tsx
> +export default function Balao({ imagem, alternativo, titulo, descricao }:Balaopropos) {
Isso, além de ficar mais abstraído (a gente só passa o objeto, sem se importar com o que tem dentro. Quem vai lidar com a lógica e o q tem dentro é o próprio componente!)

Facilita tb caso a gente queira mudar os atributos depois. 

Vamos dizer que queremos adicionar um atributo novo. 
- Da forma com que está, a gente teria que ver todos os lugares que chamam esse componente e adicionar um novo atributo. 
- Se vc passar só o objeto, não precisa mudar nada (só a lógica interna do componente!)

2024-06-02 17:13 UTC, Anemaygi commented on src/app/components/Balao.tsx
> +                            <ImageG className="w-60 h-40 rounded-3xl" src={balao.imagem} alt={balao.alternativo} />
**:hammer: Ajuste**

Por padrão, a tag <Image> do next **precisa** receber alt, src, width e height. Na prática, não vai fazer diferença na interface (pois estamos definindo o tamanho com tailwind), mas é necessário adicionar as tags de "width" e "height" com algum valor

https://nextjs.org/docs/pages/api-reference/components/image

2024-06-02 17:13 UTC, Anemaygi commented on src/app/components/Oqueeograce.tsx
> +            <ImageG className="-mb-2 w-screen" src="/home/oqueeograceBGB.svg" alt="" />
**:hammer: Ajuste**

Por padrão, a tag <Image> do next **precisa** receber alt, src, width e height. Na prática, não vai fazer diferença na interface (pois estamos definindo o tamanho com tailwind), mas é necessário adicionar as tags de "width" e "height" com algum valor

https://nextjs.org/docs/pages/api-reference/components/image

2024-06-02 17:13 UTC, Anemaygi commented on src/app/components/Oqueeograce.tsx
> +            <ImageG className="-mb-2 w-screen" src="/home/oqueeograceBGT.svg" alt="" /> {/*priorizar uso de w-screen over w-full*/}
**:hammer: Ajuste**

Por padrão, a tag <Image> do next **precisa** receber alt, src, width e height. Na prática, não vai fazer diferença na interface (pois estamos definindo o tamanho com tailwind), mas é necessário adicionar as tags de "width" e "height" com algum valor

https://nextjs.org/docs/pages/api-reference/components/image

2024-06-02 17:13 UTC, Anemaygi commented on src/app/components/Balao.tsx
> +        <div className="mt-16 grid grid-cols-3 gap-x-5 gap-y-4"> {/*não me preocupei com responsividade mas PRECISAMOS*/}
**:cloud: Sugestão**

Para os comentários que são tarefas que precisaremos fazer no futuro (como adicionar responsividade ou resolver um bug), colocar `TODO: tarefa em uma frase`

Assim, quando a gente pesquisar por "TODO" no código, conseguimos ver todos os pontos de atenção que a gente precisa ter

https://medium.com/imdoneio/the-imdone-pitch-feedback-welcome-386430accf01

2024-06-02 17:13 UTC, Anemaygi commented on public/home/oqueeograceFundo.svg
**:hammer: Ajuste**

Podemos apagar essa imagem?

2024-06-03 06:22 UTC, Anemaygi commented on src/app/components/Balao.tsx
> +export default function Balao(props: BaloesInt) {
**:cloud: Sugestão**

Colocar o nome desse componente como BalaoGrid ou algo assim, para ficar mais claro

Interface pode ser BalaoList

e a interface do BalaoObjeto pode ser só Balao

2024-06-03 23:00 UTC, segalv commented on public/home/oqueeograceFundo.svg
Sim! Achei que já tinha apagado! 
Deletei

2024-06-03 23:14 UTC, segalv commented on src/app/components/Balao.tsx
> +export default function Balao(props: BaloesInt) {
Boa!

2024-06-03 23:51 UTC, segalv commented
Mayu, acredito que eu tenha finalizado todos os ajustes e adicionado as sugestões! Você pode dar uma conferida?

2024-06-04 05:11 UTC, Anemaygi requested changes
**Arrasouuuuuuu, Ana! O código ficou lindão, tudo certinho :star_struck:** 

Agora, só adicionar responsividade e vai estar prontinho!

# :iphone: Responsividade

A responsividade é a capacidade do seu site/componente ser funcional independente do tamanho da tela (ex: seu componente não deve quebrar num celular, num tablet ou num computador)
<br/>

## :globe_with_meridians: Testando responsividade e simulando outras dimensões de tela com [devtools](https://firefox-source-docs.mozilla.org/devtools-user/)

As **devtools** são ferramentas de desenvolvimento web dentro do navegador. Com elas, é possível debugar, testar e analisar sua página!

Uma das funcionalidades é o **modo de design responsivo**, que muda as dimensões da sua página para você ver como ela ficaria em diferentes dispositivos no próprio navegador

**Para abrir as devtools:** Clique com o botão direito na página -> Inspecionar
**Para abrir o modo responsivo:** Depois de abrir as devltools, clique nesse botão no canto superior direito
![image](https://github.com/petsi-each/Grace-Website/assets/62656745/d18631c7-1ab4-4e46-ad27-e7501c27ea25)

Nesse modo, você pode definir o tamanho da tela, arrastar ou escolher um dispositivo específico para ver como seu site ficaria naquela resolução
![image](https://github.com/petsi-each/Grace-Website/assets/62656745/2378805f-a8d4-4dd4-a269-f2491f84fb70)

Assim, você pode testar como seu componente aparece em um celular (tela pequena), tablet (tela média) ou em outros tamanhos de tela. Isso é interessante, pois, conforme você vai implementando a responsividade, você pode ver como está ficando
<br/>

## :woman_technologist: Implementando responsividade com TailwindCSS

No tailwind, você pode usar prefixos na frente das classes para aplicá-las em breakpoints ("tamanhos de tela") específicos.

![image](https://github.com/petsi-each/Grace-Website/assets/62656745/20d47fb5-0fec-4cfa-9f50-6c7859b7494d)

Além disso, o tailwind é _mobile first_. Isso significa que a mudança que você faz em um breakpoint vai afetar aquele breakpoint e todos os breakpoints maiores.

**Por exemplo:**

```html
<div class="bg-red-400 md:bg-blue-500 xl:bg-yellow-500">
  Teste
</div>
```

O fundo vai ser vermelho por padrão. Se a dimensão da tela for md (o breakpoint que definimos com o prefixo) ou maior (por ex: lg),o fundo ficará azul. Se a tela for xl ou maior, o fundo ficará amarelo.

![ezgif-5-0107cd1cb9](https://github.com/petsi-each/Grace-Website/assets/62656745/ab9312eb-3523-4043-a61a-3ac692441f09)

Você pode usar isso com todas tags e propriedades do tailwind (ex: alterar a qtd de colunas num grid, alterar margin, alterar visibilidade, alterar cor...)! Basta colocar o prefixo :) 

**:books: Materiais que recomendo**
- https://tailwindcss.com/docs/responsive-design _[Documentação do Tailwind]_
- https://www.youtube.com/watch?v=XtZI-EDwD7I _[Aula de 5 min sobre responsividade em Tailwind]_

<br/>

## :dart: Por onde começar?

Uma sugestão caso não saiba como começar:

1. Coloque a página na resolução de um celular
2. Liste o que você acha que não está responsivo (ex: margem muito grande) 
3. Veja qual tag e propriedade é referente a isso no código e qual seria o valor ideal
4. Coloque o valor antigo para um breakpoint maior (ex: md) 

E faça a mesma coisa para telas md e lg :)

Lembre-se, ao final, de testar arrastar a tela de diferentes tamanhos para ter certeza que ela nunca vai quebrar! 

<br/>

> :partying_face: **Boa sorteeee!! Se precisar de ajuda ou algo não ficar claro, só avisar**

2024-07-05 17:01 UTC, segalv commented
Boa tarde, Mayu!
Muito obrigada pelo review e pelas dicas, foram super úteis!
Fiz as novas alterações e acredito que esteja tudo certinho agora! Você pode dar uma nova olhada?

2024-07-06 05:52 UTC, Anemaygi reviewed
Arrasouuuuuuuuuuuuuuuu :star_struck: 

Ficou lindo, Anaaa! Tanto o componente quanto o código, muitoooo limpinho
Parabénsss <3

2024-07-06 05:52 UTC, Anemaygi approved these changes

2024-07-06 05:52 UTC, merged