feat: add header component
petsi-each/Grace-Website pull request #9
Opened 2024-05-12 01:00 UTC by Anemaygi

# ✨ Pull Request 💻

## :dart: Detalhes do Pull Request:

Adicionei o componente header
- adicionei botao
- adicionei tal coisa

Fixes #2 

## :bomb: Alterações e breaking changes:

- Logo
- Links
- Botão

##  :camera_flash: Screenshots:

![image](https://github.com/petsi-each/Grace-Website/assets/62656745/abff76ba-3760-4416-95d1-cdaa21d9c786)

2024-05-12 01:01 UTC, Anemaygi commented
Dúvida: pq nao da certo? teste

2024-05-12 16:33 UTC, Anemaygi commented
Inspo for new responsive menu

![image](https://github.com/petsi-each/Grace-Website/assets/62656745/ddade0ff-57f0-445a-8dce-9d5f27659693)

![image](https://github.com/petsi-each/Grace-Website/assets/62656745/575abd67-d55a-4b55-a754-ebb3d413a085)

2024-05-13 14:37 UTC, gustavojun1 commented
Como a propriedade de "hover" dos botões está para aplicar uma fonte semibold, o botão "Início", por já estar em semibold, não demonstra nenhuma alteração em hover.

Adicionar ```${pathname === link.ref ? 'hover:font-bold' : 'hover:font-semibold'}``` no lugar de ```hover:font-semibold``` na linha 62 de Header.tsx resolveria esse problema, definindo uma fonte mais grossa apenas para o hover do botão de início.

2024-05-13 14:47 UTC, gustavojun1 requested changes

2024-05-13 14:47 UTC, gustavojun1 commented on src/components/Header.tsx
> +                            <a className={`mb-2 transition-all hover:font-semibold lg:my-0 lg:mx-4 xl:mx-8  ${pathname == link.ref ? 'text-vermelhoGrace font-semibold' : ''}`}
Como a propriedade de "hover" dos botões está para aplicar uma fonte semibold, o botão "Início", por já estar em semibold, não demonstra nenhuma alteração em hover.

Adicionar ```${pathname === link.ref ? 'hover:font-bold' : 'hover:font-semibold'}``` no lugar de ```hover:font-semibold``` resolveria esse problema, definindo uma fonte mais grossa apenas para o hover do botão de início.


![2024-05-13 11-41-51](https://github.com/petsi-each/Grace-Website/assets/81436626/2969b181-589a-44fe-a307-2d0b57b7d131)

2024-05-13 16:50 UTC, gustavojun1 approved these changes

2024-05-13 16:50 UTC, merged

2024-10-16 20:38 UTC, Anemaygi commented on src/app/page.tsx
> -      <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
Nao entendi pq tava desse jeito